// Generated by CoffeeScript 1.7.1
(function() {
  var onInput, onOptionsChange, options, outputEditor, setupEditors, setupGui, sourceEditor, _ref;

  setupEditors = function(onInput) {
    var outputEditor, sourceEditor;
    sourceEditor = ace.edit('source-editor');
    sourceEditor.setTheme('ace/theme/monokai');
    sourceEditor.getSession().setMode('ace/mode/javascript');
    sourceEditor.setFontSize(18);
    sourceEditor.on('input', onInput);
    outputEditor = ace.edit('output-editor');
    outputEditor.setTheme('ace/theme/monokai');
    outputEditor.getSession().setMode('ace/mode/javascript');
    outputEditor.getSession().setUseWrapMode(true);
    outputEditor.setReadOnly(true);
    outputEditor.setFontSize(18);
    return {
      sourceEditor: sourceEditor,
      outputEditor: outputEditor
    };
  };

  setupGui = function(onChange) {
    var chkHeaders, chkWrap;
    chkHeaders = document.getElementById('chk-headers');
    chkHeaders.addEventListener('change', function() {
      options.headers = this.checked;
      onChange();
    });
    chkWrap = document.getElementById('chk-wrap');
    chkWrap.addEventListener('change', function() {
      options.wrap = this.checked;
      onChange();
    });
  };

  onInput = function() {
    var newSource;
    newSource = roller.obfuscate(sourceEditor.getValue(), options);
    return outputEditor.setValue(newSource);
  };

  onOptionsChange = onInput;

  options = {};

  _ref = setupEditors(onInput), sourceEditor = _ref.sourceEditor, outputEditor = _ref.outputEditor;

  setupGui(onOptionsChange);

  AjaxUtil.load('sample1.js', function(source) {
    return sourceEditor.setValue(source, 1);
  });

}).call(this);
