// Generated by CoffeeScript 1.7.1
(function() {
  var AjaxUtil;

  AjaxUtil = {};

  AjaxUtil.load = function(url, callback) {
    var httpRequest;
    httpRequest = new XMLHttpRequest();
    httpRequest.onreadystatechange = function() {
      if (httpRequest.readyState === 4) {
        if (httpRequest.status === 200) {
          return callback(httpRequest.responseText);
        } else {
          throw new Error('Could not retrieve ' + url);
        }
      }
    };
    httpRequest.open('GET', url);
    return httpRequest.send();
  };

  window.AjaxUtil = AjaxUtil;

}).call(this);
