// Generated by CoffeeScript 1.7.1
(function() {
  var Emp, List, _base, _base1;

  Emp = {
    add: function(value) {
      return new List(value);
    },
    find: function(predicate) {
      return null;
    },
    isEmpty: function() {
      return true;
    }
  };

  List = function(value, next) {
    this.value = value;
    this.next = next != null ? next : Emp;
  };

  List.prototype.add = function(value) {
    return new List(value, this);
  };

  List.prototype.find = function(predicate) {
    if (predicate(this.value)) {
      return this;
    } else {
      return this.next.find(predicate);
    }
  };

  List.prototype.isEmpty = function() {
    return false;
  };

  if (window.roller == null) {
    window.roller = {};
  }

  if ((_base = window.roller).Emp == null) {
    _base.Emp = Emp;
  }

  if ((_base1 = window.roller).List == null) {
    _base1.List = List;
  }

}).call(this);
